# =================================================================
#
# Authors: Tom Kralidis <tomkralidis@gmail.com>
#
# Copyright (c) 2020 Tom Kralidis
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: http://localhost:5000
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    cors: true
    languages:
        # First language is the default language
        - en-US
        - fr-CA
    # cors: true
    pretty_print: true
    limit: 10
    # templates:
      # path: /path/to/Jinja2/templates
      # static: /path/to/static/folder # css/js/img
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
#    manager:
#        name: TinyDB
#        connection: /tmp/pygeoapi-process-manager.db
#        output_dir: /tmp/
    # ogc_schemas_location: /opt/schemas.opengis.net

logging:
    level: ERROR
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title:
            en: pygeoapi default instance
            fr: instance par défaut de pygeoapi
        description:
            en: pygeoapi provides an API to geospatial data
            fr: pygeoapi fournit une API aux données géospatiales
        keywords:
            en:
                - geospatial
                - data
                - api
            fr:
                - géospatiale
                - données
                - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://example.org
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Organization Name
        url: https://pygeoapi.io
    contact:
        name: Lastname, Firstname
        position: Position Title
        address: Mailing Address
        city: City
        stateorprovince: Administrative Area
        postalcode: Zip or Postal Code
        country: Country
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: you@example.org
        url: Contact URL
        hours: Mo-Fr 08:00-17:00
        instructions: During hours of service. Off on weekends.
        role: pointOfContact

resources:
    altitudine:
        type: collection
        title: Altitudine
        description: Altitudine
        keywords:
            - Mappe
            - Mappe Fisiche
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://test.org
        extents:
            spatial:
                bbox: [14.730526000,40.810341863,15.145774000,40.622234194]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        providers:
            - type: coverage
              name: rasterio
              data: data/Mappe_Fisiche/Altitudine_30-1738_EPSG4326.tif
              format:
                  name: GTiff
                  mimetype: image/tiff
    esposizione:
        type: collection
        title: Esposizione
        description: Esposizione
        keywords:
            - Mappe
            - Mappe Fisiche
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://test.org
        extents:
            spatial:
                bbox: [14.730526000,40.810341863,15.145774000,40.622234194]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        providers:
            - type: coverage
              name: rasterio
              data: data/Mappe_Fisiche/esposizione_EPSG4326.tif
              format:
                  name: GTiff
                  mimetype: image/tiff
    pendenza:
        type: collection
        title: Pendenza
        description: Pendenza
        keywords:
            - Mappe
            - Mappe Fisiche
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://test.org
        extents:
            spatial:
                bbox: [14.730526000,40.810341863,15.145774000,40.622234194]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        providers:
            - type: coverage
              name: rasterio
              data: data/Mappe_Fisiche/pendenza_EPSG4326.tif
              format:
                  name: GTiff
                  mimetype: image/tiff
    precipitazioni:
        type: collection
        title: Precipitazioni
        description: Precipitazioni
        keywords:
            - Mappe
            - Mappe Climatiche
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://test.org
        extents:
            spatial:
                bbox: [14.730526000,40.810341863,15.145774000,40.622234194]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        providers:
            - type: coverage
              name: rasterio
              data: data/mappe_climatiche/precipitaz_area_igp_giffiot.tif
              format:
                  name: GTiff
                  mimetype: image/tiff
    tmax:
        type: collection
        title: Temperatura massima
        description: Temperatura massima periodo Luglio-Agosto
        keywords:
            - Mappe
            - Mappe Climatiche
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://test.org
        extents:
            spatial:
                bbox: [14.730526000,40.810341863,15.145774000,40.622234194]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        providers:
            - type: coverage
              name: rasterio
              data: data/mappe_climatiche/t_medmax_15m-15g_area_igp_giffiot.tif
              format:
                  name: GTiff
                  mimetype: image/tiff
    tmedmax:
        type: collection
        title: Temperatura media
        description: Temperatura media periodo 15 Maggio - 15 Giugno
        keywords:
            - Mappe
            - Mappe Climatiche
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://test.org
        extents:
            spatial:
                bbox: [14.730526000,40.810341863,15.145774000,40.622234194]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        providers:
            - type: coverage
              name: rasterio
              data: data/mappe_climatiche/t_medmax_15m-15g_area_igp_giffiot.tif
              format:
                  name: GTiff
                  mimetype: image/tiff
    comuni:
        type: collection
        title: Comuni IGP
        description: Limiti comuni appartenenti al IGP
        keywords:
            - Mappe
            - Altro
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://test.org
        extents:
            spatial:
                bbox: [14.730526000,40.810341863,15.145774000,40.622234194]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        providers:
            - type: feature
              name: GeoJSON
              data: data\comuni_igp\comuni_igp.geojson
              id_field: ISTAT
    sistemi_terre:
        type: collection
        title: Sistemi terre
        description: Sistemi terre
        keywords:
            - Mappe
            - Altro
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://test.org
        extents:
            spatial:
                bbox: [14.730526000,40.810341863,15.145774000,40.622234194]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        providers:
            - type: feature
              name: GeoJSON
              data: data/sistemi_terre_t/sistemi_terre.geojson
    companies:
        type: collection
        title: Aziende
        description: Aziende
        keywords:
            - Temi
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://test.org
        extents:
            spatial:
                bbox: [14.730526000,40.810341863,15.145774000,40.622234194]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        providers:
            - type: feature
              name: OGR
              data:
                source_type: ESRI Shapefile
                source: data/aziende/Aziende.shp
                source_options:
                  ADJUST_GEOM_TYPE: FIRST_SHAPE
              id_field: PartitaIva
              layer: Aziende
    companies-lands:
        type: collection
        title: Terreni Aziende
        description: Terreni appartenenti alle aziende del IGP, con informazioni relative alla coltura
        keywords:
            - Temi
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://test.org
        extents:
            spatial:
                bbox: [14.730526000,40.810341863,15.145774000,40.622234194]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        providers:
            - type: feature
              name: GeoJSON
              data: data/terreni_aziende/TerreniAziende2.geojson
              id_field: ID
    climate-attitude:
        type: collection
        title: Attitudine climatica
        description: Mappa di attitudine climatica areale di produzione "Nocciola di Giffoni IGP"
        keywords:
            - Mappe
            - Mappe Climatiche
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://test.org
        extents:
            spatial:
                bbox: [14.730526000,40.810341863,15.145774000,40.622234194]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        providers:
            - type: feature
              name: OGR
              data:
                source_type: ESRI Shapefile
                source: data/mappa_di_attitudine_climatica_finale/mappe_clima_finali_vet.shp
                source_options:
                  ADJUST_GEOM_TYPE: FIRST_SHAPE
              id_field: fid
              layer: mappe_clima_finali_vet